<a href="https://colab.research.google.com/github/ob3x/Learn-Ds/blob/main/regresja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
raw_data = pd.read_csv("Exam_Score_Prediction.csv")
df = raw_data.copy()
df.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB

In [9]:
df = df.drop(columns=["student_id", "age", "gender", "facility_rating"])
df.head()

,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,exam_difficulty,exam_score
0,diploma,2.78,92.9,yes,7.4,poor,coaching,hard,58.9
1,bca,3.37,64.8,yes,4.6,average,online videos,moderate,54.8
2,b.sc,7.88,76.8,yes,8.5,poor,coaching,moderate,90.3
3,diploma,0.67,48.4,yes,5.8,average,online videos,moderate,29.7
4,diploma,0.89,71.6,yes,9.8,poor,coaching,moderate,43.7

In [25]:
for col in ["course", "internet_access", "sleep_quality", "study_method", "exam_difficulty"]:
  df[col] = df[col].astype("category")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   course            20000 non-null  category
 1   study_hours       20000 non-null  float64
 2   class_attendance  20000 non-null  float64
 3   internet_access   20000 non-null  category
 4   sleep_hours       20000 non-null  float64
 5   sleep_quality     20000 non-null  category
 6   study_method      20000 non-null  category
 7   exam_difficulty   20000 non-null  category
 8   exam_score        20000 non-null  float64
dtypes: category(5), float64(4)
memory usage: 723.7 KB

In [26]:
from sklearn.model_selection import train_test_split

x = df.drop(columns=["exam_score"])
y = df["exam_score"]

x_train, x_test, y_train, t_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(f"x_train shape: {x_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {t_test.shape}")

x_train shape: (16000, 8)
x_test shape: (4000, 8)
y_train shape: (16000,)
y_test shape: (4000,)

In [27]:
x_train = pd.get_dummies(x_train, columns=["course", "internet_access", "sleep_quality", "study_method", "exam_difficulty"], drop_first=True, dtype=int)
x_test = pd.get_dummies(x_test, columns=["course", "internet_access", "sleep_quality", "study_method", "exam_difficulty"], drop_first=True, dtype=int)

In [28]:
x_train

,study_hours,class_attendance,sleep_hours,course_b.sc,course_b.tech,course_ba,course_bba,course_bca,course_diploma,internet_access_yes,sleep_quality_good,sleep_quality_poor,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,exam_difficulty_hard,exam_difficulty_moderate
5894,6.87,57.1,9.0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0
3728,6.91,54.8,9.1,0,0,1,0,0,0,1,1,0,0,1,0,0,1,0
8958,5.45,99.4,7.6,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1
7671,4.73,47.6,7.0,0,0,1,0,0,0,1,0,1,1,0,0,0,0,1
5999,3.81,78.6,7.8,0,0,0,0,1,0,1,1,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,7.36,98.8,7.1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0
11964,5.83,99.0,9.6,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0
5390,1.49,80.1,7.1,0,0,1,0,0,0,1,1,0,0,1,0,0,0,1
860,0.28,52.1,7.1,0,0,0,0,1,0,1,1,0,0,0,1,0,0,1
15795,0.59,67.6,9.1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train[["study_hours", "class_attendance", "sleep_hours"]] = scaler.fit_transform(x_train[["study_hours", "class_attendance", "sleep_hours"]])
x_test[["study_hours", "class_attendance", "sleep_hours"]] = scaler.transform(x_test[["study_hours", "class_attendance", "sleep_hours"]])

In [34]:
x_train

,study_hours,class_attendance,sleep_hours,course_b.sc,course_b.tech,course_ba,course_bba,course_bca,course_diploma,internet_access_yes,sleep_quality_good,sleep_quality_poor,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study,exam_difficulty_hard,exam_difficulty_moderate
5894,1.239349,-0.756186,1.156364,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0
3728,1.256681,-0.889533,1.214028,0,0,1,0,0,0,1,1,0,0,1,0,0,1,0
8958,0.624091,1.696234,0.349059,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1
7671,0.312128,-1.306966,0.003071,0,0,1,0,0,0,1,0,1,1,0,0,0,0,1
5999,-0.086490,0.490316,0.464388,0,0,0,0,1,0,1,1,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,1.451657,1.661448,0.060735,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0
11964,0.788737,1.673043,1.502351,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0
5390,-1.091702,0.577281,0.060735,0,0,1,0,0,0,1,1,0,0,1,0,0,0,1
860,-1.615972,-1.046070,0.060735,0,0,0,0,1,0,1,1,0,0,0,1,0,0,1
15795,-1.481655,-0.147429,1.214028,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [44]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

In [45]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(t_test, y_pred)
mse

108.07812816644677

In [46]:
pd.DataFrame({"y_test": t_test, "y_pred": y_pred})

       y_test     y_pred
10650    31.1  35.631434
2041     81.6  71.735679
8668     68.0  58.917345
1114    100.0  94.181148
13902    84.8  84.604419
...       ...        ...
4073     58.6  54.773068
7442     53.3  28.841555
9999     58.8  60.931778
1870     45.3  64.672939
15196    42.7  51.372564

[4000 rows x 2 columns]